GuiEksamen/Opgave2/Opgave2/Opgave2/Models/ErrorViewModel.cs
using System;

namespace Opgave2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GuiEksamen/Opgave2/Opgave2/Opgave2/Models/HomeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Opgave2.Models
{
    using Opgave2.Model;

    [Serializable]
    public class HomeModel
    {
        public HomeModel()
        {
            ShoppingLists = LogToFile.LogToFileInstance.LoadProductsFromFile() ?? new List<ShoppingListModel>();

        }
        public List<ShoppingListModel> ShoppingLists { get; set; }
    }
}

GuiEksamen/Opgave2/Opgave2/Opgave2/Models/LogToFile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Opgave2.Model
{
    using System.Collections.ObjectModel;
    using System.Diagnostics;
    using System.IO;

    using Newtonsoft.Json;

    using Opgave2.Models;

    class LogToFile
    {
        private LogToFile() { }

        private static readonly LogToFile logToFileInstance = new LogToFile();

        public static LogToFile LogToFileInstance => logToFileInstance;

        private readonly string filepath = AppDomain.CurrentDomain.BaseDirectory + "\\ShoppingLists.json";


        public void SaveProductsToFile(List<ShoppingListModel> ProductsToSave)
        {
            if (ProductsToSave == null || ProductsToSave.Count < 1)
            {
                return;
            }
            File.WriteAllText(this.filepath, JsonConvert.SerializeObject(ProductsToSave, Formatting.Indented, new JsonSerializerSettings
                                                                                                                  {
                                                                                                                      NullValueHandling = NullValueHandling.Ignore
                                                                                                                      
                                                                                                                  }));
        }


        public List<ShoppingListModel> LoadProductsFromFile()
        {
            var ListToReturn = new List<ShoppingListModel>();
            try
            {
                ListToReturn = JsonConvert.DeserializeObject<List<ShoppingListModel>>(
                    File.ReadAllText(this.filepath),
                    new JsonSerializerSettings
                        {   
                            NullValueHandling = NullValueHandling.Ignore
                        });
                return ListToReturn;
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
                return null;
            }
        }
    }

}

GuiEksamen/Opgave2/Opgave2/Opgave2/Models/ShoppingListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Opgave2.Models
{
    public class ShoppingListModel
    {
        public List<Product> ProductList { get; set; } = new List<Product>();
        public string Name { get; set; }

        private Guid id;
        public Guid Id {
            get
            {
                if (this.id == Guid.Empty)
                {
                    this.id = Guid.NewGuid();
                }
                return this.id;
            }
            set => this.id = value;
        }
    }

    public class Product
    {
        public string ProductName { get; set; }
        public int Price { get; set; }
        public int Amout { get; set; }
    }
}

GuiEksamen/Opgave2/Opgave2/Opgave2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Opgave2.Models;

namespace Opgave2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View(new HomeModel());
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GuiEksamen/Opgave2/Opgave2/Opgave2/Controllers/ShoppingListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Opgave2.Controllers
{
    using Opgave2.Model;
    using Opgave2.Models;

    public class ShoppingListController : Controller
    {
        private HomeModel ProductListsList = new HomeModel();
        // GET: ShoppingListModel
        public ActionResult Index(Guid? Id)
        {
            ShoppingListModel newlist = null;
            if (Id == null)
            {
                newlist = new ShoppingListModel();
            }
            else
            {
                if (this.ProductListsList.ShoppingLists.Any(i => i.Id == Id))
                {
                    newlist = this.ProductListsList.ShoppingLists.Find(i => i.Id == Id);
                }
                else
                {
                    newlist = new ShoppingListModel();
                }
            }
            return View(newlist);
        }

        // POST: ShoppingListModel/Create
        [HttpPost]
        public ActionResult Create(Guid id ,int amout, string Productname, int price, string Name)
        {
            if (ModelState.IsValid)
            {
                var addList = this.ProductListsList.ShoppingLists.Find(i => i.Id == id);
                if (addList == null)
                {
                    addList = new ShoppingListModel();
                    this.ProductListsList.ShoppingLists.Add(addList);
                }
                if (amout == 0)
                {
                    var itemToRemove = addList.ProductList.Find(a => a.ProductName == Productname);
                    addList.ProductList.Remove(itemToRemove);
                    LogToFile.LogToFileInstance.SaveProductsToFile(this.ProductListsList.ShoppingLists);
                    return this.View("Index", addList);
                }
                else
                {
                    var productToAdd = new Product()
                                           {
                                               Amout = amout,
                                               ProductName = Productname,
                                               Price = price
                                           };

                    addList.Name = Name;
                    addList.ProductList.Add(productToAdd);

                    LogToFile.LogToFileInstance.SaveProductsToFile(this.ProductListsList.ShoppingLists);
                    return this.View("Index", addList);
                }               
            }
            else
            {
                return this.View("Index");
            }
        }

       
    }
}

GuiEksamen/Opgave2/Opgave2/Opgave2/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>An application done for GUI exam winter 2018. A way to manage your shopping lists</p>

GuiEksamen/Opgave2/Opgave2/Opgave2/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Tobias Kjær Henriksen<br />
    201304131<br />
    au479319<br />
    Aarhus University
</address>

<address>
    Vejlby Toften 322a<br />
    Risskov, 8240<br />
    <abbr title="Phone">P:</abbr>
    +4520746508
</address>

<address>
    <strong>E-mail:</strong> <a href="mailto:tobi.dk@gmail.com">tobi.dk@gmail.com</a><br />
</address>

GuiEksamen/Opgave2/Opgave2/Opgave2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model Opgave2.Models.HomeModel

<div>
    <h1>Welcome to the shopping list manager</h1>
</div>

<div>
    <ul>
        @foreach (var item in Model.ShoppingLists)
        {
            <li><a href="@Url.Action("Index","ShoppingList", new {item.Id})">@item.Name</a></li>
        }
    </ul>
    <p><a href="@Url.Action("index","ShoppingList")">Add new shopping list</a></p>
</div>

GuiEksamen/Opgave2/Opgave2/Opgave2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Opgave2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Opgave2</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2018 - Opgave2</p>
    </footer>
</div>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>

GuiEksamen/Opgave2/Opgave2/Opgave2/Views/ShoppingList/Index.cshtml
@model Opgave2.Models.ShoppingListModel


@using (Html.BeginForm("Create", "ShoppingList"))
{ 
@Html.HiddenFor(m => m.Id)
    <div>    
        <h2>Shopping List: <input Name="Name" type="text" value="@Model.Name"/></h2>
    </div>
    <div>
        <table>
            <tr>
                <th>Amount&nbsp;</th>
                <th>Name&nbsp;</th>
                <th>Induvidual Prices&nbsp;</th>
            </tr>
            @foreach (var p in Model.ProductList)
            {
            <tr>
                <td>@p.Amout&nbsp;</td>
                <td>@p.ProductName&nbsp;</td>
                <td>@p.Price&nbsp;</td>
            </tr>
            }
        </table>
        <p>Amout: <input Name="Amout" type="text" /> <br /> Name:&nbsp; <input Name="ProductName" type="text" /> <br /> Price:&nbsp;&nbsp; <input Name="Price" type="text" /> </p>
        <p><Button>Add shopping product</Button></p>
        <p><Button>Remove with product name and fill in 0 in Amount and Price</Button></p>
    </div>
}